const diccionario = {
  // ---------------------------------------------------------     0 - 4
  facil: [
    "HTML",
    "GIT",
    "NODE",
    "SASS",
    "LESS",
    "CSS",
    "PHP",
    "JAVA",
    "SQL",
    "DB",
    "NPM",
    "YARN",
    "API",
    "VUE",
    "MAC",
    "ATOM",
    "WEB",
    "REST",
    "RUBY",
    "DEV",
    "AWS",
    "",
  ],

  // ---------------------------------------------------------     5 - 8
  medio: [
    "GITHUB",
    "BINARIO",
    "REACT",
    "REDUX",
    "MONGODB",
    "MYSQL",
    "SERVIDOR",
    "EXPRESS",
    "PYTHON",
    "SWIFT",
    "VSCODE",
    "ANGULAR",
    "COMMIT",
    "LINUX",
    "WINDOWS",
    "UBUNTU",
    "LARAVEL",
    "JQUERY",
    "DOCKER",
    "FLASK",
    "DJANGO",
    "FLUTTER",
    "IONIC",
    "UNITY",
    "FIREBASE",
    "HEROKU",
    "NETLIFY",
    "GITLAB",
    "JENKINS",
    "CODEWARS",
    "CODEPEN",
    "",
  ],

  // ---------------------------------------------------------    9 - 12
  dificil: [
    "JAVASCRIPT",
    "TYPESCRIPT",
    "COFFESCRIPT",
    "PROGRAMADOR",
    "SEQUELIZE",
    "POSTGRESQL",
    "SUBLIME TEXT",
    "REPOSITORIO",
    "BOOTSTRAP",
    "FRAMEWORK",
    "REACT NATIVE",
    "DIGITALOCEAN",
    "KUBERNETES",
    "BITBUCKET",
    "",
  ],
};

export default diccionario